#logging:
#  level:
#    org.hibernate.SQL: DEBUG          # Hiển thị câu SQL với dấu '?'
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Hiển thị giá trị tham số
#

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    url: jdbc:postgresql://parkmanage.postgres.database.azure.com:5432/postgres
    username: postgres
    password: Loi123456
jwt:
  secret: DHiuqwbV^j@oaIUmqlHUK@_QW12dnash987234n
  expireTime: 60

server:
  port: ${WEBSITES_PORT:8080}