server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL} # jdbc:postgresql://localhost:5432/parkdb
    username: ${SPRING_DATASOURCE_USERNAME} # postgres
    password: ${SPRING_DATASOURCE_PASSWORD} # 123456
  jpa:
    hibernate:
      ddl-auto: update   # dev only; use migrations for prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG
# Prefer ENV VARS for secrets in real environments, but this works for local dev
PAYOS_CLIENT_ID: c2fbf473-2403-4441-9b9a-aec78cf39a82
PAYOS_API_KEY: 76675f43-a3cf-4311-a7f0-8316fd8ea3a9
PAYOS_CHECKSUM_KEY: e1b57c7e9f9aa99aca0322c01a8e42cc2aa8278cd0400bab13036c6c2d92fd6b

jwt:
  secret: change-me-very-long-random-string-at-least-32-bytes-11111111111111111111111
  expire-time: 86400
  issuer: change-me-issuer

gemini:
  api-key: AIzaSyDL4bvKRy3qkJz0HjihQg3PckjbU-3pb5U    # prefer env var in real use
  model: gemini-2.0-flash

app:
  internal-topup-confirm-url: http://localhost:8080/api/local/topups/confirm
  webhook:
    base-url: "https://wiring-harbor-opt-disabilities.trycloudflare.com"  # update when tunnel changes
    path: /api/payment/payos/webhook
  mail:
    fromName: Park Management